groups:
  - name: customer-success-rules
    rules:
    # General health checks
    - alert: ServiceDown
      expr: up{job="customer-success-fte"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Customer Success FTE service is down"
        description: "The Customer Success FTE service has been down for more than 1 minute."

    # High error rate
    - alert: HighErrorRate
      expr: rate(fte_http_requests_total{status_code=~"5.."}[5m]) / rate(fte_http_requests_total[5m]) > 0.05
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is above 5% for the last 5 minutes."

    # Slow response time
    - alert: SlowResponseTime
      expr: histogram_quantile(0.95, sum(rate(fte_http_request_duration_seconds_bucket[5m])) by (le)) > 3
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Slow response time detected"
        description: "95th percentile response time is above 3 seconds."

    # High customer escalation rate
    - alert: HighEscalationRate
      expr: rate(fte_escalations_total[10m]) > 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High escalation rate detected"
        description: "More than 10 escalations in the last 10 minutes."

    # Agent performance issues
    - alert: AgentSlowThinking
      expr: histogram_quantile(0.95, sum(rate(fte_agent_thinking_time_seconds_bucket[5m])) by (le)) > 30
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Agent taking too long to think"
        description: "95th percentile agent thinking time is above 30 seconds."

    # Database connectivity issues
    - alert: DatabaseConnectivityIssue
      expr: fte_database_connections_current < 1
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Database connectivity issue"
        description: "No active database connections for Customer Success FTE."

    # High message queue size
    - alert: HighMessageQueueSize
      expr: fte_message_queue_size > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High message queue size"
        description: "Message queue size is above 1000 messages."

    # Low customer satisfaction
    - alert: LowCustomerSatisfaction
      expr: avg_over_time(fte_customer_satisfaction_score[30m]) < 0.7
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Low customer satisfaction detected"
        description: "Average customer satisfaction score below 0.7 for the last 30 minutes."